### ISSUE TITLE
gradle doesn't detect the gradle.properties and build.gradle

### ISSUE THREAD

**Issue by salieri-alex** [MAJigsaw77/extension-androidtools#12]
When successfully compiling in lime, uploading the artifact in gradle is very hard to do because of extension-androidtools as gradle.properties and build.gradle isn't somehow found even though it's in the project folder of your library. Is there anything to resolve this? (JDK Temurin 17, NDK r21e and latest version of SDK are my versions)

**Comment by KarimAkra** [comment]
try downgrading you SDK to 4.4 (KitKat) or 10
i recommend using 4.4

**Comment by salieri-alex** [comment]
> try downgrading you SDK to 4.4 (KitKat) or 10 i recommend using 4.4

If you're talking about API versions, i already have installed android 4.4

**Comment by salieri-alex** [comment]
Any solution?
